### ISSUE TITLE
Unknown beeps

### ISSUE THREAD

**Issue by iam468** [ilya-fedin/hilink-tray#5]
Sometimes often app is beeping, and It`s take time to understand that beeps is from Hilink App, that it`s means some connection issues - threre are no logs (didnt found) and no opportunity to disable beeps.

Imagine - you hear two-four beeps. And you tray icon is ok (connection restored) and you as new user dont understand what application beeping sometimes

**Comment by ilya-fedin** [comment]
It plays a sound and sends a notification about unread SMS if you system supports that. Read all SMS in the HiLink interface and the app won't send notifications.

**Comment by iam468** [comment]
so each time it reconnects - it will beep for one unreaded sms? okay. will try. tnx

**Comment by ilya-fedin** [comment]
> it will beep for one unreaded sms?

It will beep for each notification. After reconnect it sends one notification that tells the number of unread SMS.

**Comment by iam468** [comment]
okay. seems not obvious for me that it`s from hilink app and it`s case of SMS (no tooltip, only anonymous sound) - but as you wish - issue can be closed
